### ISSUE TITLE
Support rootless usage of GraphDB

### ISSUE THREAD

**Issue by abhishekmaha-tno** [khaller93/graphdb-free#3]
Currently, it isn't possible to use purely non-root users for the container.

**Comment by khaller93** [comment]
Yes, you are right.

I started to work on it in the "develop" branch, but had no time to finish it.

**Comment by khaller93** [comment]
A bit late, but I added this functionality now. I hope that it works for you @abhishekmaha-tno and others. If not, feel free to reopen this issue.
