### ISSUE TITLE
Loading data into the default graph

### ISSUE THREAD

**Issue by psiotwo** [khaller93/graphdb-free#8]
What is the correct way of loading data into the default graph?

**Comment by khaller93** [comment]
Hi @psiotwo. As far as I know, the default graph in GraphDB is unnamed and doesn't appear as a result in a query like this:
```sparql
SELECT DISTINCT ?g WHERE { 
    GRAPH ?g {?s ?p ?o .}
}
```
The unnamed default graph is the union of all imported statements, so you always import data into the default graph.

Do you want to import data without a specified named graph into a graph with a specific URI? What are you trying to do? If I remember correctly, some other triplestores have a predefined URI for this case, but GrahDB doesn't do that.

**Comment by psiotwo** [comment]
INSERT does not work on onto:Explicit, but then I tried to use TriG inside toLoad and works :face_with_spiral_eyes: . Sorry
