### ISSUE TITLE
Java Compiler Not Found Exception with 9.11.2

### ISSUE THREAD

**Issue by Groebehavn** [khaller93/graphdb-free#9]
Dear Author,

First of all, thank you for the nice work for providing all these docker files! :)

I am having issues with adding any data, even from the GraphDB UI, to the container 9.11.2. The issue again is the lack of Java Compiler, addressed somehow with the addition of a full JDK, but somehow this does not work with 9.11.2. It works fine with 9.10.3 though. Could you please help me? Probably it is fine on github, just not there on docker hub, or this is the assumption we have now.

Thank you!
Thomas

**Comment by khaller93** [comment]
Hi,

> I am having issues with adding any data, even from the GraphDB UI, to the container 9.11.2.

I tried to reproduce with an ordinary repository and [poke-a.nq.gz](https://pokemonkg.org/download/dump/poke-a.nq.gz), and it worked for me. Do you have a special repository configuration with a custom ruleset?

> Probably it is fine on github, just not there on docker hub.

OntoText introduced breaking changes and I only added the new bug fixes and features to the Dockerfiles for the most recent releases. All the Dockerfiles from 1.4 only work with GraphDB 10 and upwards.

I added the JDK fix to 1.3. Here is the image: `docker.io/khaller/graphdb-free:1.3.6-graphdb9.11.2_amd64`

**Comment by Groebehavn** [comment]
Hi Kevin,
The image you linked seems to work for us, super! :)

Thank you for your help!

Bests,
Thomas
